# Сервис записи актов нарушений и база данных для журнала нарушений.
# Использует NodeJS приложение и ElasticSearch для хранения данных.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service-app
          image: docker.io/t1mondocker/audit-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_HOST
              value: "audit-db-cluster"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_NAME
              value: "audit-db"
            - name: REDIS_HOST
              value: "redis-cluster"
            - name: REDIS_PORT
              value: "6379"
        - name: audit-db-express
          image: mongo-express:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "audit-db-cluster"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "admin"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audit-db-set
  namespace: security-ns
spec:
  serviceName: audit-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: audit-db
  template:
    metadata:
      labels:
        app: audit-db
    spec:
      containers:
        - name: audit-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: audit-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: audit-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: security-ns
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: audit-db-headless
  namespace: security-ns
spec:
  selector:
    app: audit-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: audit-db-cluster
  namespace: security-ns
spec:
  selector:
    app: audit-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: audit-db-express-service
  namespace: security-ns
spec:
  selector:
    app: audit-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: mongodb-express
