apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy-app
          image: caddy:2-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - name: caddy-config-volume
              mountPath: /etc/caddy
      volumes:
        - name: caddy-config-volume
          configMap:
            name: caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  namespace: security-ns
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: security-ns
data:
  Caddyfile: |
    {
        log default {
          output stdout
          format json
          level debug
        }
    }
    
    security.local {
        encode gzip
    
        handle_path /* {
            reverse_proxy http://audit-client.security-ns:8080
        }
    
        handle_path /audit/* {
            reverse_proxy http://audit-service.security-ns:3000
        }
    
        handle /socket.io/* {
            reverse_proxy http://notification-service.security-ns:3000
        }
    }
