# Сервис контроля целостности конфигураций и база данных для эталонных конфигураций.
# Использует NodeJS приложение и MongoDB для хранения данных.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service-app
          image: docker.io/t1mondocker/config-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: host-config-service
              mountPath: /host
          env:
            - name: PORT
              value: "3000"
            - name: ROOT
              value: "/host"
            - name: INTERVAL
              value: "10"
            - name: MONGO_HOST
              value: "config-db-cluster"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_NAME
              value: "config-db"
            - name: REDIS_HOST
              value: "redis-cluster"
            - name: REDIS_PORT
              value: "6379"
        - name: config-db-express
          image: mongo-express:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "config-db-cluster"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "admin"
      volumes:
        - name: host-config-service
          hostPath:
            path: /host
            type: Directory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-db-set
  namespace: security-ns
spec:
  serviceName: config-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: config-db
  template:
    metadata:
      labels:
        app: config-db
    spec:
      containers:
        - name: config-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: config-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: config-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: security-ns
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: config-db-headless
  namespace: security-ns
spec:
  selector:
    app: config-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: config-db-cluster
  namespace: security-ns
spec:
  selector:
    app: config-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongodb-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: config-db-express-service
  namespace: security-ns
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: mongodb-express
