# Сервис отправки уведомлений о нарушениях.
# Использует NodeJS приложение.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-app
          image: docker.io/t1mondocker/notification-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: "redis-cluster"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: security-ns
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
