# Сервис контроля установки пакетов и база данных реестра пакетов.
# Использует NodeJS приложение и MongoDB для хранения данных.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: security-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-service-app
          image: node:20-alpine
          command: ["node", "-e", "console.log('Registry Service is running'); setInterval(()=>{}, 3600000)"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: host-registry-service
              mountPath: /host
        - name: registry-db
          image: mongo:latest
          volumeMounts:
            - name: registry-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: registry-db-data
          persistentVolumeClaim:
            claimName: registry-pvc
        - name: host-registry-service
          hostPath:
            path: /Users/dderbin/Desktop/kubernetes/host
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: security-ns
spec:
  selector:
    app: registry-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
