# Сервис записи актов нарушений и база данных для журнала нарушений.
# Использует NodeJS приложение и ElasticSearch для хранения данных.
apiVersion: v1
kind: Namespace
metadata:
  name: security-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-log-pvc
  namespace: security-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-log-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-log-service
  template:
    metadata:
      labels:
        app: audit-log-service
    spec:
      containers:
        - name: audit-log-service-app
          image: node:20-alpine
          command: [ "node", "-e", "console.log('Audit Log Service is running'); setInterval(()=>{}, 3600000)" ]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 8080
        - name: audit-log-db
          image: mongo:latest
          volumeMounts:
            - name: audit-log-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: audit-log-db-data
          persistentVolumeClaim:
            claimName: audit-log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
  namespace: security-ns
spec:
  selector:
    app: audit-log-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
