# Сервис контроля целостности конфигураций и база данных для эталонных конфигураций.
# Использует NodeJS приложение и MongoDB для хранения данных.
apiVersion: v1
kind: Namespace
metadata:
  name: security-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: security-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: security-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service-app
          image: node:20-alpine
          command: ["node", "-e", "console.log('Config Service is running'); setInterval(()=>{}, 3600000)"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: host-config-service
              mountPath: /host
        - name: config-db
          image: mongo:latest
          volumeMounts:
            - name: config-db-data
              mountPath: /data/db
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: config-db-data
          persistentVolumeClaim:
            claimName: config-pvc
        - name: host-config-service
          hostPath:
            path: /Users/dderbin/Desktop/kubernetes/host/config-service
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: security-ns
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
